In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.14.0


In [13]:
type("hello")

str

In [14]:
hello = tf.constant("Hello")

In [15]:
world = tf.constant("World")

In [16]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [17]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [19]:
const = tf.constant(10)

In [20]:
fill_mat = tf.fill((4,4), 10)

In [21]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
myrandn = tf.random_normal((4,4))

In [25]:
myrandu = tf.random_uniform((4,4))

In [32]:
sess = tf.InteractiveSession()

/Users/mokul791/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [33]:
my_ops = [const, myzeros, myones, fill_mat, myrandn,myrandu]

In [34]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.86448854 -0.5952443  -0.8670447   0.27452967]
 [ 1.5269566   0.7685537   0.7501261   2.4296038 ]
 [ 1.4039952   0.39931116  0.85583013 -2.092865  ]
 [-0.21277851  0.8943442   1.3213342  -0.88149077]]


[[0.13449919 0.48161662 0.37849247 0.3356005 ]
 [0.59387493 0.826056   0.9224572  0.6647382 ]
 [0.9644064  0.7436172  0.79942536 0.23206675]
 [0.9629681  0.34283662 0.81001306 0.605906  ]]




In [30]:
with tf.Session() as sess:
    for op in my_ops:
        print(sess.run(op))
        print('\n')

10


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[-0.69139826  0.06182754 -0.14639457 -1.8012466 ]
 [ 0.529272    1.9200438  -0.6200202   1.4640486 ]
 [-0.610016   -0.5771688   1.1747614  -0.03235734]
 [ 0.4361441   1.0042838   0.08576267  0.66439354]]


[[0.7409648  0.5967742  0.2923739  0.637594  ]
 [0.75076175 0.5649878  0.9846029  0.2579347 ]
 [0.58366954 0.03202331 0.14179885 0.14029884]
 [0.24319291 0.8135841  0.5652741  0.47068155]]




In [36]:
a = tf.constant([[10, 20], [30,40]])

In [37]:
type(a)

tensorflow.python.framework.ops.Tensor

In [38]:
a

<tf.Tensor 'Const_5:0' shape=(2, 2) dtype=int32>

In [41]:
b = tf.constant([[5], [7]])

In [42]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [45]:
result = tf.matmul(a, b)

In [46]:
sess.run(result)

array([[190],
       [430]], dtype=int32)

In [47]:
result.eval()

array([[190],
       [430]], dtype=int32)